/*
 *  Copyright (C) 2020-2026 Embedded AMS B.V. - All Rights Reserved
 *
 *  This file is part of Embedded Proto.
 *
 *  Embedded Proto is dual licensed. You may use it under the terms of the
 *  GNU General Public License version 3 (GPLv3) as published by the Free
 *  Software Foundation, or under a commercial license from Embedded AMS B.V.
 *
 *  Under the GPLv3 you must release the source code of
 *  any product you distribute that includes Embedded Proto or code
 *  generated by it. A commercial license removes that obligation.
 *  See <https://embeddedproto.com/pricing/>.
 *
 *  Embedded Proto is distributed WITHOUT ANY WARRANTY; without even the
 *  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the LICENSE file in the root of the repository for details.
 *
 *  SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-EmbeddedProto-Commercial
 *
 *  Embedded AMS B.V., Hoorn, the Netherlands - info at EmbeddedProto dot com
 */

#ifndef _WRITE_BUFFER_INTERFACE_H_
#define _WRITE_BUFFER_INTERFACE_H_

#include "Defines.h"

#include <cstdint>


namespace EmbeddedProto 
{
  //! The pure virtual definition of a message buffer used for writing .
  /*!
      This interface is to be used by classes wishing to use the buffer. An actual implementation
      is made specific to how you would like to store data.

      The buffer deals with bytes (uint8_t) only.
  */
  class WriteBufferInterface
  {
    public:

      WriteBufferInterface() = default;

#ifdef VIRTUAL_DESTRUCTORS_ENABLED
      virtual ~WriteBufferInterface() = default;
#else
    protected:
      //! Protected and non-virtual by default, see VIRTUAL_DESTRUCTORS_ENABLED in Defines.h.
      ~WriteBufferInterface() = default;

    public:
#endif

      //! Delete all data in the buffer.
      virtual void clear() = 0;

      //! Obtain the total number of bytes currently stored in the buffer.
      virtual uint32_t get_size() const = 0;

      //! Obtain the total number of bytes which can at most be stored in the buffer.
      virtual uint32_t get_max_size() const = 0;

      //! Obtain the total number of bytes still available in the buffer.
      /*!
          The value must never exceed the number of bytes a following push() actually
          accepts. The partial serializers write a field tag and its value as a pair on the
          strength of this value: once the tag is in the buffer the value has to fit, there
          is no way to take the tag back. A buffer over-reporting its free space breaks that
          guarantee and leaves a duplicate tag in the output on retry.

          \return The number of bytes push() can still accept.
      */
      virtual uint32_t get_available_size() const = 0;

      //! Push a single byte into the buffer.
      /*!
          \param[in] byte The data to append after previously added data in the buffer.
          \return True when there was space to add the byte.
      */
      virtual bool push(const uint8_t byte) = 0;

      //! Push an array of bytes into the buffer, all-or-nothing.
      /*!
          The given array will be appended after already added data in the buffer.
          This call is all-or-nothing: either every byte is appended and true is
          returned, or the buffer is left untouched and false is returned. The
          packed repeated field serialization depends on this contract to retry an
          element cleanly after BUFFER_FULL, so an implementation may never append
          only part of the array.
          \param[in] bytes A view on the array of bytes, bytes.size bytes are appended.
          \return True when there was space to add all the bytes.
      */
      virtual bool push(const const_bytes_view& bytes) = 0;

      //! Push an array of bytes into the buffer, pointer and length form of push(const const_bytes_view&).
      /*!
          \param[in] bytes Pointer to the array of bytes.
          \param[in] length The number of bytes in the array.
          \return True when there was space to add all the bytes.
      */
      virtual bool push(const uint8_t* bytes, const uint32_t length)
      {
        return push(const_bytes_view{bytes, length});
      }

      //! Account for a number of payload bytes without pushing their values.
      /*!
          A buffer storing data can not do this and returns false, the caller is to
          push the actual bytes. A buffer only counting bytes, like the
          MessageSizeCalculator, adds the given number to its count and returns true.
          This way the caller can skip producing a payload of which the size is
          already known.

          \param[in] number_of_bytes The number of payload bytes to account for.
          \return True when the bytes are accounted for and need not be pushed.
      */
      virtual bool count_only(const uint32_t number_of_bytes)
      {
        // Ignore the unused parameter, this buffer requires the actual data.
        (void)number_of_bytes;
        return false;
      }

  };

} // End of namespace EmbeddedProto

#endif // End of _WRITE_BUFFER_INTERFACE_H_
